
-- ----------------------------
-- Table structure for t_event_logs_v1
-- ----------------------------
DROP TABLE IF EXISTS "public"."t_event_logs_v1";
CREATE TABLE "public"."t_event_logs_v1" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
),
  "type" varchar(254) COLLATE "pg_catalog"."default",
  "block" int8,
  "global_id" varchar(254) COLLATE "pg_catalog"."default",
  "nonce" int8,
  "canister_id" varchar(254) COLLATE "pg_catalog"."default",
  "caller" varchar(254) COLLATE "pg_catalog"."default",
  "from_addr" varchar(254) COLLATE "pg_catalog"."default",
  "to_addr" varchar(254) COLLATE "pg_catalog"."default",
  "event_key" varchar(254) COLLATE "pg_catalog"."default",
  "event_value" text COLLATE "pg_catalog"."default",
  "caller_time" timestamp(6),
  "ices_time" timestamp(6),
  "index" int8
)
;
ALTER TABLE "public"."t_event_logs_v1" OWNER TO "postgres";

-- ----------------------------
-- Primary Key structure for table t_event_logs_v1
-- ----------------------------
ALTER TABLE "public"."t_event_logs_v1" ADD CONSTRAINT "t_event_logs_pkey" PRIMARY KEY ("id");



-- View
-- 1 View name-------------
-- v1_all_caller_count_7d
--------------------------
SELECT a."time",
COALESCE(c.counts, 0::bigint) AS counts
FROM ( SELECT to_char(b.b, 'YYYY-MM-DD'::text) AS "time"
FROM generate_series(CURRENT_TIMESTAMP - '6 days'::interval, CURRENT_TIMESTAMP, '1 day'::interval) b(b)
GROUP BY (to_char(b.b, 'YYYY-MM-DD'::text))
ORDER BY (to_char(b.b, 'YYYY-MM-DD'::text))) a
LEFT JOIN ( SELECT to_char(t_event_logs_v1.ices_time::timestamp with time zone, 'YYYY-MM-DD'::text) AS event_date,
count(DISTINCT t_event_logs_v1.caller) AS counts
FROM t_event_logs_v1
GROUP BY (to_char(t_event_logs_v1.ices_time::timestamp with time zone, 'YYYY-MM-DD'::text))
ORDER BY (to_char(t_event_logs_v1.ices_time::timestamp with time zone, 'YYYY-MM-DD'::text))) c ON a."time" = c.event_date



-- 2 View name------------
-- v1_all_caller_count_all
--------------------------
SELECT count(DISTINCT t.caller) AS counts
FROM t_event_logs_v1 t


-- 3 View name------------
-- v1_all_canister_count_7d
--------------------------
SELECT a."time",
COALESCE(c.counts, 0::bigint) AS counts
FROM ( SELECT to_char(b.b, 'YYYY-MM-DD'::text) AS "time"
FROM generate_series(CURRENT_TIMESTAMP - '6 days'::interval, CURRENT_TIMESTAMP, '1 day'::interval) b(b)
GROUP BY (to_char(b.b, 'YYYY-MM-DD'::text))
ORDER BY (to_char(b.b, 'YYYY-MM-DD'::text))) a
LEFT JOIN ( SELECT to_char(t_event_logs_v1.ices_time::timestamp with time zone, 'YYYY-MM-DD'::text) AS event_date,
count(DISTINCT t_event_logs_v1.canister_id) AS counts
FROM t_event_logs_v1
GROUP BY (to_char(t_event_logs_v1.ices_time::timestamp with time zone, 'YYYY-MM-DD'::text))
ORDER BY (to_char(t_event_logs_v1.ices_time::timestamp with time zone, 'YYYY-MM-DD'::text))) c ON a."time" = c.event_date


-- 4 View name------------
-- v1_all_event_count_7d
--------------------------
SELECT a."time",
COALESCE(c.counts, 0::bigint) AS counts
FROM ( SELECT to_char(b.b, 'YYYY-MM-DD'::text) AS "time"
FROM generate_series(CURRENT_TIMESTAMP - '6 days'::interval, CURRENT_TIMESTAMP, '1 day'::interval) b(b)
GROUP BY (to_char(b.b, 'YYYY-MM-DD'::text))
ORDER BY (to_char(b.b, 'YYYY-MM-DD'::text))) a
LEFT JOIN ( SELECT to_char(t_event_logs_v1.ices_time::timestamp with time zone, 'YYYY-MM-DD'::text) AS event_date,
count(t_event_logs_v1.id) AS counts
FROM t_event_logs_v1
GROUP BY (to_char(t_event_logs_v1.ices_time::timestamp with time zone, 'YYYY-MM-DD'::text))
ORDER BY (to_char(t_event_logs_v1.ices_time::timestamp with time zone, 'YYYY-MM-DD'::text))) c ON a."time" = c.event_date


-- 5 View name------------
-- v1_canister_caller_count_7d
--------------------------
SELECT a."time",
COALESCE(c.counts, 0::bigint) AS counts,
c.canister_id
FROM ( SELECT to_char(b.b, 'YYYY-MM-DD'::text) AS "time"
FROM generate_series(CURRENT_TIMESTAMP - '6 days'::interval, CURRENT_TIMESTAMP, '1 day'::interval) b(b)
GROUP BY (to_char(b.b, 'YYYY-MM-DD'::text))
ORDER BY (to_char(b.b, 'YYYY-MM-DD'::text))) a
LEFT JOIN ( SELECT to_char(t_event_logs_v1.ices_time::timestamp with time zone, 'YYYY-MM-DD'::text) AS event_date,
count(DISTINCT t_event_logs_v1.caller) AS counts,
t_event_logs_v1.canister_id
FROM t_event_logs_v1
GROUP BY t_event_logs_v1.canister_id, (to_char(t_event_logs_v1.ices_time::timestamp with time zone, 'YYYY-MM-DD'::text))
ORDER BY (to_char(t_event_logs_v1.ices_time::timestamp with time zone, 'YYYY-MM-DD'::text))) c ON a."time" = c.event_date


-- 6 View name------------
-- v1_canister_caller_count_all
--------------------------
SELECT count(DISTINCT t.caller) AS counts,
t.canister_id
FROM t_event_logs_v1 t
GROUP BY t.canister_id


-- 7 View name------------
-- v1_canister_event_count_7d
--------------------------
SELECT a."time",
COALESCE(c.counts, 0::bigint) AS counts,
c.canister_id
FROM ( SELECT to_char(b.b, 'YYYY-MM-DD'::text) AS "time"
FROM generate_series(CURRENT_TIMESTAMP - '6 days'::interval, CURRENT_TIMESTAMP, '1 day'::interval) b(b)
GROUP BY (to_char(b.b, 'YYYY-MM-DD'::text))
ORDER BY (to_char(b.b, 'YYYY-MM-DD'::text))) a
LEFT JOIN ( SELECT to_char(t_event_logs_v1.ices_time::timestamp with time zone, 'YYYY-MM-DD'::text) AS event_date,
count(t_event_logs_v1.id) AS counts,
t_event_logs_v1.canister_id
FROM t_event_logs_v1
GROUP BY t_event_logs_v1.canister_id, (to_char(t_event_logs_v1.ices_time::timestamp with time zone, 'YYYY-MM-DD'::text))
ORDER BY (to_char(t_event_logs_v1.ices_time::timestamp with time zone, 'YYYY-MM-DD'::text))) c ON a."time" = c.event_date


-- 8 View name------------
-- v1_canister_event_key_group
--------------------------
SELECT t.event_key,
t.canister_id
FROM t_event_logs_v1 t
GROUP BY t.canister_id, t.event_key
