version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dbpassword

  graphql-engine:
    image: hasura/graphql-engine
    ports:
    - "8080:8080"
    # depends_on:
    # - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:dbpassword@postgres:5432/hasura
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: ADMIN_SECRET

  ices-sync:
    image: ices-sync:v1.0.0
    restart: always
    ports:
    - "8006:8006"
    environment:
      DATABASE_URL: postgres://postgres:dbpassword@postgres:5432/ices_sync
      IC_URL: https://ic0.app
      CANISTER_ID: ydetr-mqaaa-aaaah-aa6lq-cai
      RUST_LOG: info

volumes:
  db_data:

networks:
  default:
    external:
      name: app_default